import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:boxboxd/core/theme.dart';
import 'package:boxboxd/core/models/race_list.dart';
import 'package:boxboxd/core/services/list_service.dart';
import 'package:boxboxd/features/auth/providers/auth_state.dart';
import 'package:go_router/go_router.dart';

class CreateListScreen extends ConsumerStatefulWidget {
  const CreateListScreen({super.key});

  @override
  ConsumerState<CreateListScreen> createState() => _CreateListScreenState();
}

class _CreateListScreenState extends ConsumerState<CreateListScreen> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  bool _isPublic = true;
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _createList() async {
    if (_titleController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a title')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = ref.read(currentUserProfileProvider).value;
      if (user == null) throw Exception('User not found');

      final newList = RaceList(
        id: '', // Generated by Firestore
        userId: user.id,
        username: user.name,
        userProfileImageUrl: user.photoUrl,
        title: _titleController.text,
        description: _descriptionController.text,
        races: [],
        isPublic: _isPublic,
        tags: [],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final listId = await ref.read(listServiceProvider).createList(newList);
      
      if (mounted) {
        context.pop(); // Go back to profile/lists
        context.push('/list/$listId'); // Go to the new list
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating list: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.black,
        title: const Text(
          'NEW LIST',
          style: TextStyle(
            fontWeight: FontWeight.w900,
            fontSize: 24,
            letterSpacing: 1,
            color: Colors.white,
          ),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _titleController,
              style: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
              decoration: const InputDecoration(
                labelText: 'List Title',
                labelStyle: TextStyle(color: Colors.grey),
                enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.white24)),
                focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: AppTheme.racingRed)),
              ),
            ),
            const SizedBox(height: 24),
            TextField(
              controller: _descriptionController,
              style: const TextStyle(color: Colors.white),
              maxLines: 3,
              decoration: const InputDecoration(
                labelText: 'Description',
                labelStyle: TextStyle(color: Colors.grey),
                enabledBorder: OutlineInputBorder(borderSide: BorderSide(color: Colors.white24)),
                focusedBorder: OutlineInputBorder(borderSide: BorderSide(color: AppTheme.racingRed)),
                filled: true,
                fillColor: Colors.white10,
              ),
            ),
            const SizedBox(height: 24),
            SwitchListTile(
              title: const Text('Public List', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
              subtitle: const Text('Anyone can see this list', style: TextStyle(color: Colors.grey)),
              value: _isPublic,
              onChanged: (val) => setState(() => _isPublic = val),
              activeColor: AppTheme.racingRed,
              contentPadding: EdgeInsets.zero,
            ),
            const Spacer(),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _createList,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.racingRed,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: Text(
                  _isLoading ? 'CREATING...' : 'CREATE LIST',
                  style: const TextStyle(fontWeight: FontWeight.w900, letterSpacing: 1),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
